Added signing to clearhaus postauthorizations
payfunc/service-clearhaus pull request #39
Opened 2021-04-26 13:28 UTC by robinnedergard

2021-04-26 13:34 UTC, florianebmeier approved these changes

2021-04-26 14:59 UTC, florianebmeier submitted a review, later dismissed

2021-04-27 07:37 UTC, florianebmeier requested changes

2021-04-27 07:37 UTC, florianebmeier commented on api/Configuration.ts
> +			typeof value.url == "string" &&
url check done twice

2021-04-27 08:44 UTC, florianebmeier approved these changes

2021-04-27 09:50 UTC, fredrikbryntesson approved these changes

2021-04-27 09:50 UTC, merged